---
- name: Handle ArchLinux based distributions
  block:
    - name: Archlinux | Install group packages
      pacman:
        name: "{{ packages_group[ansible_distribution] }}"
      when: packages_group is defined and packages_group[ansible_distribution] is defined
    - name: Archlinux | Install host packages
      pacman:
        name: "{{ packages[ansible_distribution] }}"
      when: packages is defined and packages[ansible_distribution] is defined
    - name: Archlinux | Create AUR Builder user
      block:
        - name: Archlinux | Create AUR Builder user
          user:
            name: "{{ aur_user | default('aur_builder') }}"
            group: wheel
            system: true
        - name: Archlinux | Let AUR Builder user invoke pacman without sudo password
          lineinfile:
            path: /etc/sudoers.d/11-install-aur_builder
            line: "{{ aur_user | default('aur_builder') }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            create: true
            validate: "visudo -cf %s"
      become: true
      when: packages_group.AUR is defined or packages.AUR is defined
    - name: Archlinux | Install AUR group packages
      kewlfft.aur.aur:
        name: "{{ item }}"
      loop: "{{ packages_group.AUR }}"
      become: true
      become_user: "{{ aur_user | default('aur_builder') }}"
      when: packages_group.AUR is defined
    - name: Archlinux | Install AUR host packages
      kewlfft.aur.aur:
        name: "{{ item }}"
      loop: "{{ packages.AUR }}"
      become: true
      become_user: "{{ aur_user | default('aur_builder') }}"
      when: packages.AUR is defined
    - name: Archlinux | Remove unwanted packages
      pacman:
        name: "{{ packages_remove[ansible_distribution] }}"
        state: absent
      when: packages_remove[ansible_distribution] is defined
