---
- name: Include distribution specific tasks
  block:
    - name: Debian | Include distribution specific tasks
      include_tasks: debian.yml
      when: ansible_distribution in ('Debian', 'Ubuntu')
    - name: SUSE | Include distribution specific tasks
      include_tasks: suse.yml
      when: ansible_distribution in ('openSUSE Tumbleweed', 'openSUSE Leap')
    - name: SUSE | Include distribution specific tasks
      include_tasks: archlinux.yml
      when: ansible_distribution in ('Archlinux')
    - name: RedHat | Include distribution specific tasks
      include_tasks: redhat.yml
      when: ansible_distribution in ('Fedora', 'Red Hat Enterprise Linux', 'CentOS')
  become: true

